-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.softcartdimcategory
(
    category_id integer NOT NULL,
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    create_at timestamp without time zone DEFAULT now(),
    CONSTRAINT softcartdimcategory_pkey PRIMARY KEY (category_id),
    CONSTRAINT softcartdimcategory_category_key UNIQUE (category)
);

CREATE TABLE IF NOT EXISTS public.softcartdimcountry
(
    country_id integer NOT NULL,
    country character varying(50) COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp without time zone DEFAULT now(),
    CONSTRAINT softcartdimcountry_pkey PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS public.softcartdimdate
(
    date_id integer NOT NULL,
    full_date date NOT NULL,
    year integer NOT NULL,
    quarter integer NOT NULL,
    quarter_name character varying(2) COLLATE pg_catalog."default" NOT NULL,
    month integer NOT NULL,
    month_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    day integer NOT NULL,
    day_of_week integer NOT NULL,
    day_of_week_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_weekend boolean NOT NULL,
    CONSTRAINT softcartdimdate_pkey PRIMARY KEY (date_id)
);

CREATE TABLE IF NOT EXISTS public.softcartdimitem
(
    item_id integer NOT NULL,
    item character varying(50) COLLATE pg_catalog."default" NOT NULL,
    category_id integer NOT NULL,
    price numeric(10, 1) NOT NULL,
    description text COLLATE pg_catalog."default",
    create_at timestamp without time zone DEFAULT now(),
    update_at timestamp without time zone DEFAULT now(),
    CONSTRAINT softcartdimitem_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.softcartfactsales
(
    order_id integer NOT NULL,
    date_id integer NOT NULL,
    item_id integer NOT NULL,
    country_id integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    quantity integer NOT NULL,
    create_at timestamp without time zone DEFAULT now(),
    update_at timestamp without time zone DEFAULT now(),
    CONSTRAINT softcartfactsales_pkey PRIMARY KEY (order_id)
);

ALTER TABLE IF EXISTS public.softcartdimitem
    ADD CONSTRAINT softcartdimitem_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.softcartdimcategory (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.softcartfactsales
    ADD FOREIGN KEY (country_id)
    REFERENCES public.softcartdimcountry (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.softcartfactsales
    ADD FOREIGN KEY (item_id)
    REFERENCES public.softcartdimitem (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.softcartfactsales
    ADD FOREIGN KEY (date_id)
    REFERENCES public.softcartdimdate (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;